apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name | default "pccs" }}
  labels:
    {{- include "pccs.labels" . | nindent 4 }}
spec:
  {{- $svcType := default "ClusterIP" .Values.service.type }}
  type: {{ $svcType }}
  {{- if and (eq $svcType "ClusterIP") .Values.service.headless }}
  clusterIP: None
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: pccs-https-port
      protocol: TCP
      {{- if and (eq $svcType "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "pccs.selectorLabels" . | nindent 4 }}
